services:
  - type: web
    name: amplify-concert-server
    env: node
    region: frankfurt
    plan: free
    rootDir: concert-server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
